// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXcvuCA9V4OG76pDp57Iy0W2y2VPgGmNA',
    appId: '1:661881998478:web:77a46ca555a8a872a08ddf',
    messagingSenderId: '661881998478',
    projectId: 'first-aj-flutter-app',
    authDomain: 'first-aj-flutter-app.firebaseapp.com',
    storageBucket: 'first-aj-flutter-app.appspot.com',
    measurementId: 'G-B5TXVMEMZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGTXaa6fm3_feEm5d85U5cHwDuXKvbVks',
    appId: '1:661881998478:android:b17ca8b255a4b582a08ddf',
    messagingSenderId: '661881998478',
    projectId: 'first-aj-flutter-app',
    storageBucket: 'first-aj-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_kc1AHMG7ydwgA5F1eNQf36YlzAbG6u0',
    appId: '1:661881998478:ios:7cf9974c5f92521ba08ddf',
    messagingSenderId: '661881998478',
    projectId: 'first-aj-flutter-app',
    storageBucket: 'first-aj-flutter-app.appspot.com',
    iosClientId: '661881998478-fpbaabqab36g7tgoes87jco6j57dgu47.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_kc1AHMG7ydwgA5F1eNQf36YlzAbG6u0',
    appId: '1:661881998478:ios:7cf9974c5f92521ba08ddf',
    messagingSenderId: '661881998478',
    projectId: 'first-aj-flutter-app',
    storageBucket: 'first-aj-flutter-app.appspot.com',
    iosClientId: '661881998478-fpbaabqab36g7tgoes87jco6j57dgu47.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNotes',
  );
}
